### ISSUE TITLE
Login fails if we use the netrc strategy and there is no netrc file present.

### ISSUE THREAD

**Issue by betolink** [nsidc/earthaccess#195]
```python
import earthaccess 
print(f"using earthaccess version {earthaccess.__version__}")

auth = earthaccess.login(strategy="netrc")
```

The code in earthaccess/api just passes the null auth object to the store and then it breaks. A fix is in progress.

**Comment by JessicaS11** [comment]
I just came to report this... let me know if I can help!

**Comment by andypbarrett** [comment]
I can see a number of solutions to this.

1. Raise an exception with a message that guides users to how to create a .netrc.  Something like FileNotFoundError(".netrc not found.  See https://how_to_create_a_netrc")
2. Raise a warning with a similar message to above and then fall-back to entering EDL creds from cmd line.
3.  Similar to 2 but allow .netrc to be created.

2 and 3 assume that earthaccess will be used interactively.  1 allows for earthaccess to be used from a script.  My preference is for 1 because I can see that one valuable use case for eathaccess is creating reproducible workflows.

**Comment by betolink** [comment]
I agree Andy, I think 2 things are needed: 
1. What you suggested, if a user explicitly uses `strategy=netrc` and for some reason `earthaccess` cannot locate the `.netrc`, we should rise an exception with the error message.
2. earthaccess should automatically fallback if no strategy is provided i.e.

```python
import earthaccess

auth = earthaccess.login() 
```
should try the environment first, then the netrc and lastly ask the user for credentials if both fail. 
What do you both think?

**Comment by JessicaS11** [comment]
I like the idea of raising an error if the user specifies netrc but doesn't have one.

> should try the environment first, then the netrc and lastly ask the user for credentials if both fail.
> What do you both think?

I think I would try netrc, then environment, then command line. I don't know how universal this is, but at least for Hackweeks we've tended to recommend the netrc method of storing credentials, because it doesn't require the user to have an understanding of environment variables (what they are, how to automatically set them, etc., especially in a shared hub environment). I'm sure the computational difference is minimal, but I think we should order them by what the average user is most likely to have set up.

**Comment by jhkennedy** [comment]
> I think I would try netrc, then environment, then command line.

I would want the order to be exactly the opposite :rofl: . That is, I want to be able to easily override my default `.netrc` credentials without having to edit the `.netrc` file so that I can change between testing accounts. And I think, at least for the CLI ones, since a user would have explicitly provided them, you should just use them.

If using the `.netrc` is going to be a *hard* requirement (might be needed for distributed computing), then, I'd still allow CLI/ENV variables and write them to the `.netrc` for users, but raise an error if there is a `.netrc` already and the credentials don't match (or even just if there is a `.netrc` already since it can store many different credentials).

**Comment by betolink** [comment]
Just to clarify, we can use any mechanism explicitly, we can safely use `interactive` and override the `.netrc` credentials. I think the `environment` first makes sense for programmatic access, i.e. AWS uses the environment variables if they are set and if not, it tries to find the `aws_config` file. Another advantage of using the environment first is on CI, we can inject those and use earthaccess to render the notebooks without having to inject a .netrc file. For most users this will be transparent (if they have a netrc with EDL credentials)
