### ISSUE TITLE
What is the primary documentation site for `earthaccess`?

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/earthaccess#277]
We currently publish documentation to two places, and our references in this repository are mixed:

* https://nsidc.github.io/earthaccess/ (from GitHub's "About" section, and several links in our README)
* https://earthdata.readthedocs.io/ (from our README badge)

RTD provides some nice features like PR previews (discussion in #275), but also the RTD URL is from the old project name. And RTD doesn't support changing URLs. If we really want to use RTD, we might consider deleting and re-creating the RTD site in the admin panel as soon as possible. Maybe if we email them they can set up a redirect.

https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-my-project-slug-the-url-your-docs-are-served-at

**Comment by jrbourbeau** [comment]
I don't have a strong opinion beyond using a consistent link

> but also the RTD URL is from the old project name.

You already know this, but the recent work you and @betolink did now have the docs rendered at https://earthaccess.readthedocs.io/ 

I have a _slight_ preference for the readthedocs URL because of its familiarity, but really am fine either way

**Comment by mfisher87** [comment]
I think I also prefer readthedocs as our primary doc page. It's going to be what people use for previewing PRs, and it has "docs" in the name, so it's more self-explanatory than the "github.io" link. @betolink if you agree, let's do a quick search/replace and close this out :)

**Comment by mfisher87** [comment]
Thanks James :) I really like that idea! I'd strongly prefer to have only one doc site to worry about and completely delete our corresponding GHA workflow if we can solve everyone's concerns about broken links. @betolink @asteiker thoughts? 

It's unfortunate that we'd still need to have that `gh-pages` branch stick around. Since it wouldn't be regularly updated, I wouldn't see it in my history-visualization alias, so I think I'd be able to ignore it :)

**Comment by mfisher87** [comment]
@betolink How do you feel about James' suggestion above? I'd like to implement :)

**Comment by betolink** [comment]
Since readthedocs is the authoritative place for Python documentation, I'd say let's go ahead and use it now that we fixed its deployment! @mfisher87

**Comment by mfisher87** [comment]
I'll get started on cleaning up some PRs and implementing @jrbourbeau 's solution. `gh-pages` branch will be overwritten to have one commit with one file: `index.html`. I love the simplicity of this, thanks you James :)

**Comment by mfisher87** [comment]
The redirect behavior (GH Pages -> RTD) is now live :partying_face:
