### ISSUE TITLE
importing earthaccess from a new conda environment gives TqdmWarning: IProgress not found

### ISSUE THREAD

**Issue by itcarroll** [nsidc/earthaccess#539]
I created a new conda environment with earthaccess and ipykernel on the openscapes hub with the Python runtime, and added it to the jupyterlab kernelspecs. Importing earthaccess gives:
```
[/srv/conda/envs/oceandata/lib/python3.12/site-packages/tqdm/auto.py:21](https://openscapes.2i2c.cloud/srv/conda/envs/oceandata/lib/python3.12/site-packages/tqdm/auto.py#line=20): TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
```
I can see arguments against including ipywidgets as a dependency, and this is just a warning, but I can see it raising concerns and questions.

**Comment by jhkennedy** [comment]
`tqdm` assumes `ipywidgets` is installed if it's running in a conda environment, but that's not always true. I wrote up a decent description here:
https://github.com/ASFHyP3/hyp3-sdk/issues/92

In the HyP3 SDK we check for `ipywidgets`  when trying to import it and fall back to the non-widget version if it doesn't exist:
https://github.com/ASFHyP3/hyp3-sdk/blob/develop/src/hyp3_sdk/util.py

I don't see `tqdm` being used by Earthaccess, however, so it's likely an upstream dependency issue. Can you post the rest of the stack trace so I can see where it's being hit?

**Comment by jhkennedy** [comment]
Oh sorry, I see it's just a warning, and it's coming from tqdm itself. IMO this warning is fine and good; and much better than the hard crashing it used to do in conda environment on JupyterHub's with only `ipykernel`

**Comment by mfisher87** [comment]
`tqdm` is a transitive dependency through `pqdm`

**Comment by jhkennedy** [comment]
Minimal reproducable example is:
```shell
mamba create -n tmp python tqdm ipython ipkernel
conda activate tmp
```
And in a notebook, if you're on a JupyterHub that auto-discovers kernels, you can run a simple loop to see the behavior:
![image](https://github.com/nsidc/earthaccess/assets/7882693/7933a51e-1c5a-47f0-a058-4da4b99419ef)

Installing `jupyter` or `ipywidgets` into the conda environment will get you the normal tqdm progress bar:
![image](https://github.com/nsidc/earthaccess/assets/7882693/199e3862-a468-4244-9813-53840b835b90)
 

So using `tqdm.auto` or `tqdm.autonotebook` does the right thing here:
* detects it's in a notebook but that ipywidgets isn't installed
* warns that ipywidgets doesn't exist
* gives you back the standard shell progress bar instead of the fancy notebook one 

and `pqdm` is using `tqdm.auto`, so I don't think there's really anything to do here as it's not an Earthaccess thing. @itcarroll is it fine to close this?

**Comment by itcarroll** [comment]
Makes sense, thanks for the demo.
