### ISSUE TITLE
Some docstring cleanup

### ISSUE THREAD

**Issue by danielfromearth** [nsidc/earthaccess#590]
A couple of additional docstring suggestions pulled from [this comment](https://github.com/nsidc/earthaccess/pull/580#issuecomment-2150346317) in PR #580:
- I think this [comment for `rebuild_auth()`](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/auth.py#L50) can be put into the method docstring instead
- there's an out-dated and unnecessary [type annotation here](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/auth.py#L96) that can be removed
- I think Google docstring style prefers a spacing between summary line and expanded description (see [examples here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)). Here are the places I found that look like a line spacing could be added:
  - in [refresh_tokens()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/auth.py#L135)
  - in [get_s3_credentials()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/auth.py#L191)
  - in the two hits methods: [hits()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/search.py#L117) and [hits()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/search.py#L471)
  - in [provider()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/search.py#L563)
  - in [set_requests_session()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/store.py#L167)
  - in [get_fsspec_session()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/store.py#L267)
  - in [get_requests_session()](https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/store.py#L284)

**Comment by mfisher87** [comment]
Thanks @danielfromearth !

**Comment by Sherwin-14** [comment]
@danielfromearth Hey Daniel, I had some doubts regarding this issue. First of all, on removing the type annotations means we'll have to remove all the instances in the code related to isn't that the case? I just wanted some clarity over this.  Also the kerchunk.py has two public functions and in the issue description  you had suggested that we'll need to add the "Placeholder" to only one public function in there. So which one is it? It will help a lot if you chime in.

**Comment by mfisher87** [comment]
I think what we're looking for is on this line:

https://github.com/Sherwin-14/earthaccess/blob/f8901ade489c8c211658ec13a5757ce1b6259ff9/earthaccess/auth.py#L96

there's a docstring type annotation indicating the type of `system` is `Env`. In Python code without real type annotations, this can be useful, but since we have real type annotations, we don't need that. It's also incorrect, the real type of `system` is `Optional[System]`. So we're just looking to remove the docstring type annotation.

Personally, I think we should _not_ add `Placeholder` anywhere else. We used that solely to enable docstrings with metadata but without a subject line to not be borked by the code formatter, since adding a subject line was not in scope of that PR.
